# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for snap
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'
  pod 'AlamofireImage'

  target 'snapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'snapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
